version: 2

neon-build: &neon-build-anchor
  steps:
    - checkout
    - run:
        name: Install Rust
        command: |
          curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
          sh /tmp/rustup.sh -y

    - restore_cache:
        keys:
          - npm-dependencies-{{ checksum "yarn.lock" }}
          - npm-dependencies-

    - run:
        name: Install deps
        command: |
          yarn install --dev

    - save_cache:
        paths:
          - node_modules
        key: npm-dependencies-{{ checksum "yarn.lock" }}

    - run:
        name: Build and test
        command: |
          yarn package
          yarn test

    - run:
        name: Publish
        command: |
          yarn upload-binary

jobs:
  build_v12:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    <<: *neon-build-anchor

  build_v13:
    docker:
      - image: circleci/node:13

    working_directory: ~/repo

    <<: *neon-build-anchor

  build_v14:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    <<: *neon-build-anchor

workflows:
  version: 2
  build:
    jobs:
      - build_v12
      - build_v13
      - build_v14